# Dockerfile.lb
FROM golang:1.25-alpine AS builder

WORKDIR /app

# Go modules first for better caching
COPY go.mod go.sum ./
RUN go mod download

# Then the rest of the source
COPY . .

# Build load balancer binary
RUN CGO_ENABLED=0 GOOS=linux go build -o /lb ./cmd/lb

# Runtime image
FROM alpine:3.20

WORKDIR /app
COPY --from=builder /lb /app/lb

ENTRYPOINT ["/app/lb"]
